require 'hadope_backend'
require_relative './lib/shared_methods.rb'
require_relative './lib/gpu.rb'
require_relative './lib/data_set.rb'
require_relative './lib/map.rb'
require_relative './lib/filter.rb'
